name: eleu
description: Eleu language core.
publish_to: 'none'
version: 23.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  code_editor: ^1.3.2  
  code_text_field: ^1.1.0
  intl: ^0.18.1
  archive: ^3.3.7
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
