name: eleu_lang_cli
description: A sample command-line application.
version: 23.1.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  eleu:
    path: "../eleu"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
